### PR TITLE
Feature/router bgp

### PR DESCRIPTION
**Pull request by shebang42**
add local_as* and description to iosxr_router_bgp_neighbor_group data-source and resource
add bgp_router_id and use_neighbor_group to iosxr_router_bgp_vrf data-source and resource

tests:
```
(base) ➜  ~/src/github/terraform-provider-iosxr git:(feature/router-bgp) ✗ 
> go test -v ./... -run RouterBGPVRF 
?       github.com/CiscoDevNet/terraform-provider-iosxr [no test files]
?       github.com/CiscoDevNet/terraform-provider-iosxr/internal/provider/client        [no test files]
?       github.com/CiscoDevNet/terraform-provider-iosxr/internal/provider/helpers       [no test files]
=== RUN   TestAccDataSourceIosxrRouterBGPVRFAddressFamily
--- PASS: TestAccDataSourceIosxrRouterBGPVRFAddressFamily (32.76s)
=== RUN   TestAccDataSourceIosxrRouterBGPVRFNeighborAddressFamily
--- PASS: TestAccDataSourceIosxrRouterBGPVRFNeighborAddressFamily (14.85s)
=== RUN   TestAccDataSourceIosxrRouterBGPVRF
--- PASS: TestAccDataSourceIosxrRouterBGPVRF (7.06s)
=== RUN   TestAccIosxrRouterBGPVRFAddressFamily
--- PASS: TestAccIosxrRouterBGPVRFAddressFamily (32.87s)
=== RUN   TestAccIosxrRouterBGPVRFNeighborAddressFamily
--- PASS: TestAccIosxrRouterBGPVRFNeighborAddressFamily (18.54s)
=== RUN   TestAccIosxrRouterBGPVRF
--- PASS: TestAccIosxrRouterBGPVRF (10.13s)
PASS
ok      github.com/CiscoDevNet/terraform-provider-iosxr/internal/provider       118.247s
```

### CODE REVIEW

**Comment by shebang42** [comment]
Do you have an update if/when this can be merged?  It will simplify our workflow if we can use the official binary, since we have to use a local binary for this provider in our pipeline.

**Comment by tomvrugt** [comment]
> Do you have an update if/when this can be merged? It will simplify our workflow if we can use the official binary, since we have to use a local binary for this provider in our pipeline.

@danischm Can you please have a look at this PR?

**Review by danischm — APPROVED** [review]

**Comment by tomvrugt** [comment]
@danischm can you please create a new release that contains this fix? Thanks!

**Comment by danischm** [comment]
Done

**Pull request merged**
